### ISSUE TITLE
Verificación de auxilios duplicados

### ISSUE THREAD

**Issue by memignone** [siemunlam/web#3]
Al ingresar una ubicación, se verifica entre los auxilios actuales (NO finalizados) si existe otro auxilio con una ubicación cercana (según un parámetro a establecer). De ser así, se muestra al operador la/s posibles duplicaciones, con sus motivos y horarios de solicitud para que éste decida si se trata del mismo o no.
En caso positivo, se carga en el auxilio ya registrado previamente una solicitud con el nuevo horario.
En caso negativo, se procede con la carga de la solicitud corriente.

**Comment by fcorrales** [comment]
Se paso al excel de tareas a realizar. Cualquier cosa reabrir.
